#!/bin/bash

# Exit if there's an error
set -e

# Check arguments
if [ "$#" -lt 2 ]; then
    echo "ERROR: Need at least 2 arguments: filename, first pair, [last pair]"
    exit 1
fi

FILE="$1"
FIRST="$2"
LAST="$3"

if [ "$#" -lt 3 ]; then
    LAST="$FIRST"
fi

# Get filename without extra fluff
FNAME=$(echo "$FILE" | rev | cut -d'/' -f 1 | cut -d'.' -f 2 | rev)
EXT=$(echo "$FILE" | rev | cut -d'.' -f 1 | rev)

awk -F '[, ]' -v file="$FNAME" -v ext="$EXT" -v first="$FIRST" -v last="$LAST" '/PAIR/{pair=$3}{if (pair >= first && pair <= last) print > (file "_p" pair "." ext)}' "$FILE"

echo "Separated files saved as "$FNAME"_p#.dat"
